export const catalog = [
  {
    "_id": "60eac4341e70700ee41a5551",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "1",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5552",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "2",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5553",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "3",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5554",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "4",
    "owner": "60ea6a424eb8de324419b970"
  },

  {
    "_id": "60eac4341e70700ee41a5555",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "5",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5556",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "6",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5557",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "7",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5558",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "8",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5559",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "9",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5560",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "10",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5561",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://b1.filmpro.ru/c/455897.700xp.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "11",
    "owner": "60ea6a424eb8de324419b970"
  },
  {
    "_id": "60eac4341e70700ee41a5562",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://www.film.ru/sites/default/files/styles/thumb_1024x450/public/trailers_frame/the_hobbit_an_unexpected_journey.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "12",
    "owner": "60ea6a424eb8de324419b970"
  },

]
