export const BASE_URL = "api.sergeypopov.nomoredomains.rocks";
export const BEAT_FILMS_URL = "https://api.nomoreparties.co/beatfilm-movies";
export const BEAT_FILMS_IMAGE_URL = "https://api.nomoreparties.co";

export const catalog = [
  {
    "_id": "60eac4341e70700ee41a5551",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "1",
    "owner": "60ea6a424eb8de324419b970",
    "saved": true,
  },
  {
    "_id": "60eac4341e70700ee41a5552",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "2",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5553",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 120,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "3",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5554",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "4",
    "owner": "60ea6a424eb8de324419b970",
    "saved": true,
  },

  {
    "_id": "60eac4341e70700ee41a5555",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "5",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5556",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "6",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5557",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "7",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5558",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "8",
    "owner": "60ea6a424eb8de324419b970",
    "saved": true,
  },
  {
    "_id": "60eac4341e70700ee41a5559",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "9",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5560",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "10",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },
  {
    "_id": "60eac4341e70700ee41a5561",
    "country": "США",
    "director": "Джеймс Кэмерон",
    "duration": 162,
    "year": "2009",
    "description": "Это новый мир",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/avatar.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "nameRU": "Аатар",
    "nameEN": "Avatar",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/4/4b/Avatar-2009.jpg",
    "movieId": "11",
    "owner": "60ea6a424eb8de324419b970",
    "saved": true,
  },
  {
    "_id": "60eac4341e70700ee41a5562",
    "country": "США",
    "director": "Питер Джексон",
    "duration": 169,
    "year": "2012",
    "description": "From the smallest beginnings come the greatest legend",
    "image": "https://raw.githubusercontent.com/sergey-popov-1964/images/main/hobbit.jpg",
    "trailer": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "nameRU": "Хоббит",
    "nameEN": "The Hobbit",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/ru/3/32/The_Hobbit._An_Unexpected_Journey.jpg",
    "movieId": "12",
    "owner": "60ea6a424eb8de324419b970",
    "saved": false,
  },

]
